# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:
    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [146]:
import numpy as np

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. Comment on the type of its elements.

In [147]:
# YOUR CODE HERE

my_array1 = np.array([1, 2, 3, 4, 5], dtype = np.int64)
print(f"shape of my_array1: {my_array1.shape}")
print(f"type of my_array1: {my_array1.dtype}")

# use object type to store elements of mixed type in a numpy array
my_array2 = np.array(["account_1", 100, "account_2", 200], dtype = object)
print(f"shape of my_array2: {my_array2.shape}")
print(f"type of my_array2: {my_array2.dtype}")

shape of my_array1: (5,)
type of my_array1: int64
shape of my_array2: (4,)
type of my_array2: object


---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [148]:
# YOUR CODE HERE

my_array3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(my_array3.shape)
print(my_array3.size)       # size represents the number of elements in the array
print(my_array3.dtype)

(2, 4)
8
int64


---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features. 

Print the shape of the array.

In [149]:
# already defined first and second inputs
num_samples = 100
num_features = 17

# YOUR CODE HERE
tabular_array = np.random.random((num_samples, num_features))
print(tabular_array.shape)

(100, 17)


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [150]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

# YOUR CODE HERE
image_data = np.random.random((num_images, num_rows, num_cols, num_channels))
print(image_data.shape)

(100, 256, 256, 3)


---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over elements in the array. Print the output.

In [151]:
# YOUR CODE HERE
my_array4 = np.random.randint(10, size = (3, 2))

print(my_array4.shape)
print(my_array4.sum())
print(my_array4.sum(axis=0))
print(my_array4.sum(axis=1))
print(my_array4[0,])
print(my_array4[1,])
print(my_array4[1, 0])

my_array4[2, 1] = 10
print(my_array4)

for x in np.nditer(my_array4):
    print(x)


(3, 2)
35
[22 13]
[15  7 13]
[9 6]
[4 3]
4
[[ 9  6]
 [ 4  3]
 [ 9 10]]
9
6
4
3
9
10


You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) empty numpy array
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [152]:
# YOUR CODE HERE
a = np.random.rand(3, 2)
print(a)

b = np.arange(1991, 2018)
print(b)

c = np.empty((3, 5, 10))
print(c)

d = np.ones(shape = (3, 5, 10))
print(d)

e = 5 * np.ones(shape = (3, 3))
print(e)

f = np.random.normal(loc = 0, scale = 1, size = 10)
print(f)


[[0.57281228 0.53403895]
 [0.66869277 0.86371304]
 [0.10115908 0.70845544]]
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
[[[6.24466631e-310 6.24466631e-310 5.48645777e-310 5.48645777e-310
   6.24466611e-310 6.24463901e-310 6.24466488e-310 6.24466611e-310
   6.24463901e-310 6.24466601e-310]
  [6.24466611e-310 6.24463901e-310 6.24465788e-310 6.24466611e-310
   6.24466411e-310 6.24466614e-310 6.24466611e-310 6.24466614e-310
   6.24466619e-310 6.24466614e-310]
  [6.24466611e-310 6.24466614e-310 6.24466614e-310 6.24466488e-310
   6.24466488e-310 6.24466488e-310 6.24466601e-310 6.24465788e-310
   6.24466488e-310 6.24463901e-310]
  [6.24466617e-310 6.24466611e-310 6.24466617e-310 6.24466439e-310
   6.24466611e-310 6.24466611e-310 6.24466611e-310 6.24466611e-310
   6.24466611e-310 6.24466614e-310]
  [6.24466617e-310 6.24466617e-310 6.24466617e-310 6.24466617e-310
   6.24466611e-310 6.24466617e-310 6.24

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [153]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d;
2. Convert the years_3d array to a flat 1D array. Call this array years_1d;
3. Add a new axis (in front) to the years_1d array. Call this array years_2d;
4. Remove the first axis from years_2d array. Call this array years_1d.

For each exercise print the array and its shape.

In [154]:
# YOUR CODE HERE
years_3d = np.reshape(years, (3, 3, 3))
print(f"\nyears_3d shape={years_3d.shape}")
print(years_3d)

years_1d = years_3d.flatten()
print(f"\nyears_1d shape={years_1d.shape}")
print(years_1d)

years_2d = years_1d[np.newaxis, :]
print(f"\nyears_2d shape={years_2d.shape}")
print(years_2d)

years_1d = np.squeeze(years_2d, axis=0)
print(f"\nyears_1d shape={years_1d.shape}")
print(years_1d)


years_3d shape=(3, 3, 3)
[[[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]]

years_1d shape=(27,)
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]

years_2d shape=(1, 27)
[[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
  2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]]

years_1d shape=(27,)
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [155]:
# YOUR CODE HERE
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.array([[7, 8]])

print(f"{a = }")
print(f"{b = }")
print(f"{c = }")
print("-"*50)

print(f"{np.concatenate((a, b), axis = None) = }")
print(f"{np.concatenate((a, b), axis = 0) = }")
print(f"{np.concatenate((a, b, c), axis = 0) = }")
print(f"{np.concatenate((a, b.T), axis = 1) = }")
print("-"*50)
print()

x = np.array([1, 2])
y = np.array([3, 4])
print(f"{x = }")
print(f"{y = }")
print("-"*50)

print(f"{np.stack((x, y)) = }")
print(f"{np.stack((x, y), axis = 0) = }")
print(f"{np.stack((x, y), axis = 1) = }")
print(f"{np.stack((x, y), axis = -1) = }")


a = array([[1, 2],
       [3, 4]])
b = array([[5, 6]])
c = array([[7, 8]])
--------------------------------------------------
np.concatenate((a, b), axis = None) = array([1, 2, 3, 4, 5, 6])
np.concatenate((a, b), axis = 0) = array([[1, 2],
       [3, 4],
       [5, 6]])
np.concatenate((a, b, c), axis = 0) = array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])
np.concatenate((a, b.T), axis = 1) = array([[1, 2, 5],
       [3, 4, 6]])
--------------------------------------------------

x = array([1, 2])
y = array([3, 4])
--------------------------------------------------
np.stack((x, y)) = array([[1, 2],
       [3, 4]])
np.stack((x, y), axis = 0) = array([[1, 2],
       [3, 4]])
np.stack((x, y), axis = 1) = array([[1, 3],
       [2, 4]])
np.stack((x, y), axis = -1) = array([[1, 3],
       [2, 4]])


---
#### <span style="color:chocolate">Numpy broadcasting</span> 

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [156]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [157]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [158]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [159]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [160]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[2.37281923e-01, 8.72005547e-01, 9.89537574e-01, 9.44649530e-01],
       [2.59047822e-02, 2.41036029e-01, 2.09232762e-01, 6.91936843e-01],
       [7.02465192e-01, 5.92360703e-01, 2.85496978e-01, 9.10061264e-02],
       [4.74607622e-01, 2.44213847e-01, 3.08055169e-02, 6.55060658e-01],
       [9.80750478e-04, 4.46020788e-01, 9.63664756e-01, 3.86439740e-01],
       [4.09421652e-01, 2.32061314e-02, 3.67139198e-02, 3.02058733e-01],
       [9.58056443e-01, 7.91801052e-01, 5.15142500e-01, 9.26690622e-02],
       [6.01623233e-01, 4.45338123e-01, 8.85537478e-01, 7.66971472e-01],
       [4.99193674e-01, 5.89632232e-02, 5.72399954e-01, 2.03701092e-01],
       [4.48716641e-01, 3.28975282e-01, 4.14938107e-01, 6.23857395e-01]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [161]:
np.random.seed(seed=1)

# YOUR CODE HERE
col_mean = np.mean(my_array, axis = 0, keepdims = True)
print(f"mean of columns: {col_mean}")

col_std = np.std(my_array, axis = 0, keepdims = True)
print(f"std of columns: {col_std}")

standardized_my_array = (my_array - col_mean) / col_std
print(f"Standardize my_array = \n{standardized_my_array}")
print(f"shape Standardize my_array = {standardized_my_array.shape}")


mean of columns: [[0.43582519 0.40439207 0.49034695 0.47583507]]
std of columns: [[0.27825136 0.27021169 0.34356667 0.28503262]]
Standardize my_array = 
[[-0.71353925  1.73054494  1.45296581  1.64477478]
 [-1.47320181 -0.60454839 -0.81822313  0.75816507]
 [ 0.95827025  0.69563471 -0.5962452  -1.35012245]
 [ 0.13937912 -0.59278792 -1.33756119  0.62878976]
 [-1.56277561  0.15405964  1.37765927 -0.31363191]
 [-0.09489096 -1.41069374 -1.32036393 -0.60967173]
 [ 1.8768327   1.43372397  0.07217099 -1.34428825]
 [ 0.59585707  0.15153323  1.15025863  1.02141434]
 [ 0.22773827 -1.27836382  0.23882701 -0.95474677]
 [ 0.04633023 -0.27910262 -0.21948825  0.51931716]]
shape Standardize my_array = (10, 4)


----
#### <span style="color:chocolate">Bonus question:</span> Advanced (20 points)

Consider the following image:

In [162]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

[[0.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]


(5, 5)

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by using a border of size 2;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [163]:
# YOUR CODE HERE
print(f"Crop with border of 1: \n{my_image[1:-1, 1:-1]}")

print(f"\nCrop with border of 2: \n{my_image[2:-2, 2:-2]}")

print(f"\nReverse the column order: \n{my_image[:, ::-1]}")

Crop with border of 1: 
[[0.24 0.28 0.32]
 [0.44 0.48 0.52]
 [0.64 0.68 0.72]]

Crop with border of 2: 
[[0.48]]

Reverse the column order: 
[[0.16 0.12 0.08 0.04 0.  ]
 [0.36 0.32 0.28 0.24 0.2 ]
 [0.56 0.52 0.48 0.44 0.4 ]
 [0.76 0.72 0.68 0.64 0.6 ]
 [0.96 0.92 0.88 0.84 0.8 ]]
